name: anx_reader
description: "An e-book reader."
publish_to: 'none'

version: 1.15.0+6324

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  file_picker: any
  path_provider: ^2.1.2
  image: ^4.3.0
  sqflite_common_ffi:
    path: ../sqflite/sqflite_common_ffi
  sqflite:
    path: ../sqflite/sqflite
  path: ^1.9.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  flutter_gen_runner: 5.4.0
  intl: ^0.18.1
  flutter_colorpicker: ^1.0.3
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  archive: ^3.6.1
  flutter_inappwebview:
    path: ../flutter_inappwebview/flutter_inappwebview
  shelf: ^1.4.1
  fl_chart: ^0.67.0
  graphview:
    path: ../graphview
  flutter_rating_bar: ^4.0.1
  permission_handler: ^11.3.1
  webdav_client:
    git:
      url: https://github.com/Anxcye/webdav_client.git
  fluttertoast: ^8.2.6
  dio: ^5.4.3+1
  pubspec_parse: ^1.2.3
  logging: ^1.2.0
  flutter_file_dialog: ^3.0.2
  contentsize_tabbarview:
    git:
      url: https://github.com/Anxcye/contentsize_tabbarview.git
      ref: feat/animation
  wakelock_plus: ^1.2.5
  icons_plus: ^5.0.0
  url_launcher: ^6.2.6
  battery_plus: ^5.0.0
  flutter_tts: ^3.8.3
  sticky_headers: ^0.3.0+2
  photo_view: ^0.15.0
  flutter_smart_dialog: ^4.9.8+1
  saver_gallery: any

  share_plus: any
  device_info_plus: ^10.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  chinese_font_library: ^1.2.0
  flex_color_scheme: ^7.3.1
  sqlite3_flutter_libs: ^0.5.26
  flutter_reorderable_grid_view: ^5.4.0
  uuid: ^4.5.1
  desktop_drop: ^0.4.0
  audio_service:
    path: ../audio_service/audio_service
  # audio_session: 0.1.21
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.1
  flutter_heatmap_calendar:
    git:
      url: https://github.com/Anxcye/flutter_heatmap_calendar
  csv: ^6.0.0
  fast_gbk: ^1.0.0
  window_manager: ^0.4.3
  screen_retriever: ^0.2.0
  pretty_dio_logger: ^1.4.0
  dio_intercept_to_curl: ^0.2.0
  flutter_gemini: any
  gpt_markdown:
    path: ../gpt_markdown
  flutter_math_fork: 
    path: ../flutter_math
  pointer_interceptor: ^0.10.1+2
  connectivity_plus: ^6.1.3
  http: 1.1.2
  web_socket_channel: any
  crypto: ^3.0.3
  audioplayers: ^6.4.0
  in_app_purchase: ^3.1.5
  asn1lib: ^1.6.2
  in_app_purchase_storekit: ^0.3.15
  charset: ^2.0.1
  flutter_slidable: ^3.1.0
  cached_network_image:
    path: ../flutter_cached_network_image/cached_network_image
  lpinyin: ^2.0.3
  mongol: ^8.0.0
  introduction_screen: ^3.1.17
  flutter_floating_bottom_bar: ^1.3.0
  langchain: any
  langchain_anthropic: any
  langchain_google: any
  langchain_openai: any
    # git:
    #   url: https://github.com/Anxcye/langchain_dart.git
    #   ref: bb06c17ca667a906e3e37154b0bda95023d0c9bd
    #   path: packages/langchain_openai
  langchain_core: any
  skeletonizer: ^1.4.1
  scrollable_positioned_list: ^0.3.8
  math_expressions: ^2.5.0
  share_handler: ^0.0.25
  vibration: ^3.1.4
  staggered_reorderable:
    git:
      url: https://github.com/Anxcye/staggered_reorderable.git
      ref: 2ac799a6eeb5da74bf5080a2ba2057272fa52b78
  haptic_feedback: ^0.6.4+2
  in_app_purchase_android: ^0.3.5

dependency_overrides:
#  langchain:
#    git:
#      url: https://github.com/Anxcye/langchain_dart.git
#      ref: 310fb6b3
#      path: packages/langchain
#  langchain_core:
#    git:
#      url: https://github.com/Anxcye/langchain_dart.git
#      ref: 310fb6b3
#      path: packages/langchain_core
#  langchain_openai:
#    git:
#      url: https://github.com/Anxcye/langchain_dart.git
#      ref: 310fb6b3
#      path: packages/langchain_openai
#  langchain_anthropic:
#    git:
#      url: https://github.com/Anxcye/langchain_dart.git
#      ref: 310fb6b3
#      path: packages/langchain_anthropic
  meta: 1.11.0
  collection: 1.18.0
  characters: 1.3.0
  async: 2.11.0
  crypto: 3.0.3
  web:
    path: ../web/web
#  analyzer: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: any
  build_runner: any
  custom_lint: any
  riverpod_generator: any
  riverpod_lint: any
  freezed: ^2.4.0
  json_serializable: any
#  flutter_launcher_icons: ^0.11.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/SourceHanSerifSC-Regular.otf
    - pubspec.yaml
    - assets/foliate-js/index.html
    - assets/foliate-js/dist/
    - assets/foliate-js/src/
    - assets/foliate-js/src/vendor/
    - assets/foliate-js/src/vendor/pdfjs/
    - assets/foliate-js/src/vendor/prism/
    - assets/foliate-js/src/vendor/prism/components/
    - assets/foliate-js/src/vendor/prism/themes/
    - assets/images/
    - assets/images/book_share/
    - assets/images/bgimg/
    - assets/icon/
    - assets/CHANGELOG.md

  fonts:
    - family: SourceHanSerif
      fonts:
        - asset: assets/fonts/SourceHanSerifSC-Regular.otf
          weight: 400
        - asset: assets/fonts/SourceHanSerifSC-Bold.otf
          weight: 700
